name: Docker Publish CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build image
        run: |
          docker.build ./service-registry -t marcoweel/tw_service_registry:latest
    
